export default function TOS() {
  return (
    <main className="flex flex-col items-center justify-center p-6 space-y-6">
      <h1 className="text-3xl font-bold">Privacy Policy</h1>
      <div className="w-full max-w-2xl space-y-8">
        <section>
          <p className="text-gray-600 dark:text-gray-400">
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You. We use Your Personal data to provide and improve the
            Service. By using the Service, You agree to the collection and use
            of information in accordance with this Privacy Policy. This Privacy
            Policy has been created with the help of the Free Privacy Policy
            Generator.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold">Interpretation</h2>
          <p className="text-gray-600 dark:text-gray-400">
            Interpretation The words of which the initial letter is capitalized
            have meanings defined under the following conditions. The following
            definitions shall have the same meaning regardless of whether they
            appear in singular or in plural.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold">Definitions</h2>
          <p className="text-gray-600 dark:text-gray-400">
            {`For the purposes of this Privacy Policy: Account means a unique account created for You to access our Service or parts of our Service. Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority. Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Notion Plotter. Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses. Country refers to: Kerala, India Device means any device that can access the Service such as a computer, a cellphone or a digital tablet. Personal Data is any information that relates to an identified or identifiable individual. Service refers to the Website. Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used. Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit). Website refers to Notion Plotter, accessible from https://www.notionplotter.com You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable`}
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold">Types of Data Collected</h2>
          <h3 className="text-xl font-medium">Personal Data</h3>
          <p className="text-gray-600 dark:text-gray-400">
            While using Our Service, We may ask You to provide Us with certain
            personally identifiable information that can be used to contact or
            identify You. Personally identifiable information may include, but
            is not limited to: Email address First name and last name Usage Data
          </p>
        </section>
        <section>
          <h3 className="text-xl font-medium">Usage Data</h3>
          <p className="text-gray-600 dark:text-gray-400">
            Usage Data is collected automatically when using the Service. Usage
            Data may include information such as Your Device Internet Protocol
            address (e.g. IP address), browser type, browser version, the pages
            of our Service that You visit, the time and date of Your visit, the
            time spent on those pages, unique device identifiers and other
            diagnostic data. When You access the Service by or through a mobile
            device, We may collect certain information automatically, including,
            but not limited to, the type of mobile device You use, Your mobile
            device unique ID, the IP address of Your mobile device, Your mobile
            operating system, the type of mobile Internet browser You use,
            unique device identifiers and other diagnostic data. We may also
            collect information that Your browser sends whenever You visit our
            Service or when You access the Service by or through a mobile
            device.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold">
            Tracking Technologies and Cookies
          </h2>
          <p className="text-gray-600 dark:text-gray-400">
            We use Cookies and similar tracking technologies to track the
            activity on Our Service and store certain information. Tracking
            technologies used are beacons, tags, and scripts to collect and
            track information and to improve and analyze Our Service. The
            technologies We use may include: Cookies or Browser Cookies. A
            cookie is a small file placed on Your Device. You can instruct Your
            browser to refuse all Cookies or to indicate when a Cookie is being
            sent. However, if You do not accept Cookies, You may not be able to
            use some parts of our Service. Unless you have adjusted Your browser
            setting so that it will refuse Cookies, our Service may use Cookies.
            Web Beacons. Certain sections of our Service and our emails may
            contain small electronic files known as web beacons (also referred
            to as clear gifs, pixel tags, and single-pixel gifs) that permit the
            Company, for example, to count users who have visited those pages or
            opened an email and for other related website statistics (for
            example, recording the popularity of a certain section and verifying
            system and server integrity). Cookies can be &quot;Persistent&quot;
            or &quot;Session&quot; Cookies. Persistent Cookies remain on Your
            personal computer or mobile device when You go offline, while
            Session Cookies are deleted as soon as You close Your web browser.
            Learn more about cookies on the Free Privacy Policy website article.
            We use both Session and Persistent Cookies for the purposes set out
            below: Necessary / Essential Cookies Type: Session Cookies
            Administered by: Us Purpose: These Cookies are essential to provide
            You with services available through the Website and to enable You to
            use some of its features. They help to authenticate users and
            prevent fraudulent use of user accounts. Without these Cookies, the
            services that You have asked for cannot be provided, and We only use
            these Cookies to provide You with those services. Cookies Policy /
            Notice Acceptance Cookies Type: Persistent Cookies Administered by:
            Us Purpose: These Cookies identify if users have accepted the use of
            cookies on the Website. Functionality Cookies Type: Persistent
            Cookies Administered by: Us Purpose: These Cookies allow us to
            remember choices You make when You use the Website, such as
            remembering your login details or language preference. The purpose
            of these Cookies is to provide You with a more personal experience
            and to avoid You having to re-enter your preferences every time You
            use the Website. For more information about the cookies we use and
            your choices regarding cookies, please visit our Cookies Policy or
            the Cookies section of our Privacy Policy.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold">Use of Your Personal Data</h2>
          <p className="text-gray-600 dark:text-gray-400">
            All material and services available and/or provided by our App, its
            affiliates, employees, licensors or other commercial partners
            including, but not limited to: our logo, visual designs or other
            materials and components are the property of our App or other
            parties that have licensed their material or provided services to
            us. Such material and services are duly protected by registered and
            unregistered copyright, trademarks, trade secrets, design and such
            other intellectual property laws as may be applicable in your
            country, and may not be duplicated under any circumstances, or used
            other than for your personal non-commercial use, or otherwise than
            described in these Terms and Conditions or our Privacy Policy. We
            care about data privacy and security. By using our App, you agree to
            be bound by our Privacy Policy, which is incorporated into these
            T&C. Please be advised the Site is hosted in the INDIA. If you
            access the Site from the USA, Canada, EU, Asia, or any other region
            of the world with laws or other requirements governing personal data
            collection, use, or disclosure that differ from applicable laws in
            INDIA, then through your continued use of the Site, you are
            transferring your data to INDIA, and you expressly consent to have
            your data transferred to and processed in INDIA. If you do not agree
            with such transfer of data, you should immediately refrain from
            using our App and notify us in order to delete your data. Further,
            we do not knowingly accept, request, or solicit information from
            children or knowingly market to children. We only collect
            information from children after obtaining prior consent from their
            parents or guardians and reserve ourselves the right to suspend or
            delete your account if we suspect such consent is not authentic.
            Therefore, in accordance with the U.S. Children’s Online Privacy
            Protection Act and EU GDPR Reg. 679/2016 recitals 38 and 58, if we
            receive actual knowledge that anyone under the age of 13 has
            provided personal information to us without the requisite and
            verifiable parental consent, we will delete that information from
            the App as quickly as is reasonably practical.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold"> LIMITATION OF LIABILITY</h2>
          <p className="text-gray-600 dark:text-gray-400">
            WE WILL NOT BE LIABLE TO YOU FOR ANY LOST PROFITS OR CONSEQUENTIAL,
            SPECIAL, PUNITIVE, INDIRECT, OR INCIDENTAL DAMAGES RELATING TO,
            ARISING OUT OF, OR IN ANY WAY IN CONNECTION WITH OUR TERMS, US, OR
            OUR APP, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH
            DAMAGES. OUR AGGREGATE LIABILITY RELATING TO, ARISING OUT OF, OR IN
            ANY WAY IN CONNECTION WITH OUR TERMS, US, OR OUR SERVICES WILL NOT
            EXCEED THE GREATER OF ONE HUNDRED DOLLARS ($100) AND 100% OF THE
            PRICE PAID, IF APPLICABLE. THE FOREGOING DISCLAIMER OF CERTAIN
            DAMAGES AND LIMITATION OF LIABILITY WILL APPLY TO THE MAXIMUM EXTENT
            PERMITTED BY APPLICABLE LAW. THE LAWS OF SOME STATES OR
            JURISDICTIONS MAY NOT ALLOW THE DISCRETIONARY EXCLUSION OR
            LIMITATION OF CERTAIN DAMAGES, SO SOME OR ALL OF THE EXCLUSIONS AND
            LIMITATIONS SET FORTH ABOVE MAY NOT APPLY TO YOU. NOTWITHSTANDING
            ANYTHING TO THE CONTRARY IN OUR TERMS, IN SUCH CASES, THE LIABILITY
            OF NOTION PLOTTER [HTTPS://WWW.NOTIONPLOTTER.COM] WILL BE LIMITED TO
            THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold">INDEMNIFICATION</h2>
          <p className="text-gray-600 dark:text-gray-400">
            You agree to defend, indemnify, and hold harmless Notion Plotter
            [https://www.notionplotter.com] from and against all liabilities,
            damages, losses, and expenses of any kind (including reasonable
            legal fees and costs) relating to, arising out of, or in any way in
            connection with any of the following: (a) your access to or use of
            our Services, including information provided in connection
            therewith; (b) your breach or alleged breach of our Terms; or (c)
            any misrepresentation made by you. You will cooperate as fully as
            required by us in the defense or settlement of any claim.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold">DISPUTE RESOLUTION </h2>
          <p className="text-gray-600 dark:text-gray-400">
            In compliance with the EU-US Privacy Shield Principles and the
            Swiss-US Privacy Shield Principles, we commit to resolve complaints
            about your privacy and our collection or use of your personal
            information. European Union, United Kingdom, or Swiss individuals
            with inquiries or complaints regarding this terms of service should
            contact us by email at NICK@NOTIONPLOTTER.COM or by any other
            available method available in the CONTACT US section. Notion Plotter
            [https://www.notionplotter.com] has further committed to refer
            unresolved privacy complaints under the EU-US Privacy Shield
            Principles and the Swiss-US Privacy Shield Principles to an
            independent dispute resolution mechanism, the BBB EU PRIVACY SHIELD,
            operated by BBB National Programs. If you do not receive timely
            acknowledgment of your complaint, or if your complaint is not
            satisfactorily addressed, please visit
            https://bbbprograms.org/privacy-shield-complaints/ for more
            information and to file a complaint. This service is provided at no
            cost to you. Please do not submit GDPR complaints to BBB EU Privacy
            Shield. If your EU-US Privacy Shield complaint cannot be resolved
            through these described channels, under certain conditions, you may
            invoke binding arbitration for some residual claims not resolved by
            other redress mechanisms. To learn more, please view the Privacy
            Shield Annex 1 at
            https://www.privacyshield.gov/article?id=ANNEX-I-introduction.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold"> DISCLAIMER: WARRANTY</h2>
          <p className="text-gray-600 dark:text-gray-400">
            To the extent permitted under Applicable laws, you acknowledge that
            we provide the App as-is without any warranty of any kind, express
            or implied, and to the maximum extent permitted by Applicable law.
            We disclaim all warranties, whether express, implied, or statutory,
            including but not limited to, warranties of merchantability, fitness
            for a particular purpose, title, quiet enjoyment, accuracy, and
            non-infringement. We do not guarantee any specific results from the
            use of our App. We make no warranty that the App shall be
            uninterrupted, free of viruses, or other harmful code, timely,
            secure or error or bug free.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold">AMENDMENTS</h2>
          <p className="text-gray-600 dark:text-gray-400">
            We reserve the sole right to amend, repeal, modify, replace,
            terminate or make changes to this T&C, and the App without notice,
            from time to time. If we make material changes to this T&C, or the
            App, we shall – if possible - notify you by sending you an e-mail at
            your primary email address or in any other way convenient for us.,
            as mentioned in your account details. Any changes to this T&C, or
            App, shall be effective immediately for new users of our App;
            otherwise these changes shall be effective upon the earliest of
            thirty (30) calendar days following our dispatch of an e-mail notice
            to you; if you do not want to agree to such changes, you shall
            refrain from using the App and delete your account unless otherwise
            provided in the aforementioned notice. You are responsible at all
            times for updating your Account to provide to us your most current
            e-mail address. If the last e-mail address that you have provided to
            us is not valid, or for any reason is not capable of delivering the
            notice described above, our dispatch of the e-mail containing such
            notice shall nonetheless constitute effective notice of the changes.
            Continued use of the App following notice of such changes shall
            indicate your acknowledgement of, and T&C to be bound by, such
            changes.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold">
            {" "}
            SEVERABILITY AND DISCLAIMERS
          </h2>
          <p className="text-gray-600 dark:text-gray-400">
            Neither the rights nor the obligations arising under this T&C are
            assignable by you, and any such attempted assignment or transfer
            shall be void and without effect. We reserve the right to freely
            assign this T&C. The United Nations Convention on Contracts for the
            International Sale of Goods shall not apply to this T&C. Any notice
            to you may be provided by email to the address you have registered
            with us. We shall have no responsibility to provide maintenance or
            support services with respect to the App. If any provision of this
            T&C is unenforceable, such provision shall be interpreted to
            accomplish the objectives of such provision to the greatest extent
            possible under applicable law and the remaining provisions shall
            continue in full force and effect. All waivers by us shall be
            effective only if in writing, there included this T&C. Any waiver or
            failure by Notion Plotter [https://www.notionplotter.com] to enforce
            any provision of this T&C on one occasion shall not be deemed a
            waiver of any other provision or of such provision on any other
            occasion. You acknowledge that the App contains valuable trade
            secrets, trademarks, copyrights, proprietary information and other
            intellectual properties of Notion Plotter
            [https://www.notionplotter.com] , that any actual or threatened
            breach of any section of this T&C that may constitute irreparable
            harm to Notion Plotter [https://www.notionplotter.com] shall be
            liable to any and every damages, including but not limited to,
            incidental damages, consequential damages, nominal damages,
            liquidated damages, punitive damages, monetary or any special kind
            of damages permitted by applicable laws, as an appropriate remedy
            for such breach. This T&C and the Terms constitute the final,
            complete, and exclusive agreement between the parties regarding the
            App and supersede all prior or contemporaneous agreements,
            understandings, and communication, whether written or oral. If any
            provision of these T&C is unenforceable, such provision shall be
            interpreted to accomplish the objectives of such provision to the
            greatest extent possible under applicable law and the remaining
            provisions shall continue in full force and effect.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold">CONTACT US</h2>
          <p className="text-gray-600 dark:text-gray-400">
            For any questions or queries regarding this Terms of Service, please
            feel free to contact us: NICK@NOTIONPLOTTER.COM
          </p>
        </section>
      </div>
    </main>
  );
}
